function Animated_Carrousell() {
  return (
    <>
      <ul className="flex items-center justify-end overflow-hidden [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll">
        <li>
          <img
            src="https://www.vectorlogo.zone/logos/angel/angel-ar21.svg"
            alt="Disney"
          />
        </li>
        <li>
          <img
            src="https://www.vectorlogo.zone/logos/habitica/habitica-ar21.svg"
            alt="Disney"
          />
        </li>
        <li>
          <img
            src="https://www.vectorlogo.zone/logos/freebsd/freebsd-ar21.svg"
            alt="Airbnb"
          />
        </li>
        <li>
          <img
            src="https://www.vectorlogo.zone/logos/includeos/includeos-ar21.svg"
            alt="Apple"
          />
        </li>
        <li>
          <img
            src="https://www.vectorlogo.zone/logos/samsung/samsung-ar21.svg"
            alt="Samsung"
          />
        </li>
        <li>
          <img
            src="https://www.vectorlogo.zone/logos/quora/quora-ar21.svg"
            alt="Quora"
          />
        </li>
        <li>
          <img
            src="https://www.vectorlogo.zone/logos/sas/sas-ar21.svg"
            alt="Sass"
          />
        </li>
        <li>
          <img
            src="https://www.vectorlogo.zone/logos/airbnb/airbnb-ar21.svg"
            alt="Sass"
          />
        </li>
        <li>
          <img
            src="https://www.vectorlogo.zone/logos/apple/apple-ar21.svg"
            alt="Sass"
          />
        </li>
      </ul>
    </>
  );
}

export default Animated_Carrousell;
